---
# - name: Compress directory /root/project/backend into /home/ubuntu/backend
#   become: yes
#   archive:
#     path: /root/project/backend
#     dest: /home/ubuntu/backend.tar.gz
    
# - name: Copy backend dist files web server
#   copy:
#     src: /root/project/backend/backend.tar.gz
#     dest: /home/ubuntu/backend

# - name: Untar backend dist files web server
#   unarchive:
#     src: /home/ubuntu/backend.tar.gz
#     dest: /home/ubuntu/project/backend
    
# - name: Copy backend dist files web server
#   copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

- name: Build Node
  shell: |
    cd /root/project/backend
    npm i
    npm run build
  become: true
  become_user: root


- name: Executing node
  shell: |
    cd /root/project/backend
    pm2 start npm --name backend -- start
  become: true
  become_user: root
