---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy backend dist files web server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: Build Node
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build

- name: Executing node
  shell: |
    pm2 start backend