---
- name: Compress directory /path/to/foo/ into /path/to/foo.tgz
  archive:
    path: /root/project/backend
    dest: /home/ubuntu/backend.tar.gz
    
# - name: Copy backend dist files web server
#   copy:
#     src: /root/project/backend/backend.tar.gz
#     dest: /home/ubuntu/backend

- name: Untar backend dist files web server
  unarchive:
    src: /home/ubuntu/backend.tar.gz
    dest: /home/ubuntu/backend
    
# - name: Copy backend dist files web server
#   copy:
#     src: /root/project/backend
#     dest: /home/ubuntu

- name: Build Node
  shell: |
    cd /home/ubuntu/backend
    npm i
    npm run build

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
